app:
  build: .
  volumes:
    - ./:/go/src/github.com/stone/gotaserver
    - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
